# Copyright 2025 Intel Corporation
# Copyright 2025 Naturalis Biodiversity Center
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Server authentication functions for AnnFlux
"""

import os
from flask_httpauth import HTTPBasicAuth
from werkzeug.security import check_password_hash


auth = HTTPBasicAuth()

# space separated list of entries generated by make_password_entry.py
users = dict([x_.split("|") for x_ in os.getenv("USERS", "").split()])


@auth.verify_password
def verify_password(username, password):
    """Verify user password for authentication."""
    if len(users) == 0 or (
        username in users and check_password_hash(users.get(username, ""), password)
    ):
        return username
    return None
